[package]
name = "midgard-rs"
version = "0.0.5"
edition = "2021"
categories = ["api-bindings", "cryptography::cryptocurrencies"]
license = "MIT"
keywords = ["thorswap", "migard", "thorchain", "api"]
readme = "README.md"
description = "Thorchain Midgard API client for Rust"
repository = "https://github.com/physics515/midgard-rs"

[dependencies]
serde = { version = "1", features = ["derive", "rc"] }
reqwest = { version = "0.12" }
thiserror = { version = "1" }
anyhow = { version = "1" }
serde_json = { version = "1" }
tokio = { version = "1", features = ["full"] }
serde_urlencoded = { version = "0.7" }
rand = { version = "0.8" }
serde-aux = { version = "4" }
chrono = { version = "0.4", features = ["serde"] }
serde_with = { version = "3", features = ["chrono"] }
rust_decimal = { version = "1", features = ["serde", "serde-str"] }
tokio-test = { version = "0.4" }
